### ISSUE TITLE
@primaryKey annotation is not working as expected

### ISSUE THREAD

**Issue by omarbelkhodja** [angel-dart/angel#112]
When a model is created by Angel, an integer Id field is added automatically. I would like to specify my own id field. I have tried the following, by I got an error :

```dart
@serializable
@orm
abstract class _Permission extends Model {
  @primaryKey
  String get permission;
  int get roleId;
}

@serializable
@orm
abstract class _Role extends Model {
  int get userId;
  @primaryKey
  String get role;
  @hasMany
  List<_Permission> get permissions;
}

@serializable
@orm
abstract class _User extends Model {
  String get name;
  @primaryKey
  String get email;
  String get password;
  @hasMany
  List<_Role> get roles;
}
```

```bash
# dart bin/migrate.dart up
Bringing up "D:\\Projects\\agenda_culturel_new\\backend\\lib\\src\\models\\greeting.g.dart#GreetingMigration"...
Bringing up "D:\\Projects\\agenda_culturel_new\\backend\\lib\\src\\models\\show.g.dart#ShowMigration"...
Bringing up "D:\\Projects\\agenda_culturel_new\\backend\\lib\\src\\models\\show.g.dart#ShowPropertyMigration"...
Bringing up "D:\\Projects\\agenda_culturel_new\\backend\\lib\\src\\models\\show.g.dart#ShowDateMigration"...
Bringing up "D:\\Projects\\agenda_culturel_new\\backend\\lib\\src\\models\\user.g.dart#UserMigration"...
Bringing up "D:\\Projects\\agenda_culturel_new\\backend\\lib\\src\\models\\user.g.dart#PermissionMigration"...
Unhandled exception:
PostgreSQLSeverity.error 42P16: multiple primary keys for table "permissions" are not allowed
#0      _PostgreSQLConnection&Object&_PostgreSQLExecutionContextMixin._enqueue (package:postgres/src/connection.dart:402:24)
<asynchronous suspension>
#1      _PostgreSQLConnection&Object&_PostgreSQLExecutionContextMixin.execute (package:postgres/src/connection.dart:345:12)
#2      PostgresSchema.run (package:angel_migration_runner/src/postgres/schema.dart:14:61)
#3      PostgresMigrationRunner.up (package:angel_migration_runner/src/postgres/runner.dart:69:22)
<asynchronous suspension>
#4      _UpCommand.run (package:angel_migration_runner/src/cli.dart:25:28)
#5      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#7      new Future.sync (dart:async/future.dart:224:31)
#8      CommandRunner.run (package:args/command_runner.dart:112:14)
#9      runMigrations (package:angel_migration_runner/src/cli.dart:12:14)
#10     main (file:///D:/Projects/agenda_culturel_new/backend/bin/migrate.dart:21:16)
<asynchronous suspension>
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

The generated classes seems to be ignoring the `@primaryKey` annotation.

**Comment by thosakwe** [comment]
It is not being ignored. Like I mentioned in the previous issue, you must remove `extends Model` to provide your own primary key. Otherwise, one is given by default.
