### ISSUE TITLE
mount controller but got error is not a class, and therefore cannot be instantiated

### ISSUE THREAD

**Issue by u007** [angel-dart/angel#123]
```
import 'dart:async';
import 'package:angel_framework/angel_framework.dart';
import './user_controller.dart';

Future configureServer(Angel app) async {
  await app.mountController<UserController>();

  /// Controllers will not function unless wired to the application!
}

```

user controller class
```
import 'package:angel_framework/angel_framework.dart';
import 'package:sqljocky5/sqljocky.dart';
import '../../model/user.dart';

@Expose("/users")
class UserController extends Controller {
  final MySqlConnection sqlConn;

  UserController(this.sqlConn);

  @Expose("/:user_id")
  getUser(String user_id) async {
    final userBean = new UserBean(sqlConn);
    User user = await userBean.find(user_id);

    return user;
  }

  // You can return a response handler, and have it run as well. :)
  // @Expose("/login")
  // login() => auth.authenticate('google');
}


```

**Comment by thosakwe** [comment]
Please paste your stack trace, as without it, it’s hard to diagnose the problem.

**Comment by u007** [comment]
```
Unhandled exception:
UserController is not a class, and therefore cannot be instantiated.
#0      Container.make (package:angel_container/src/container.dart:136:7)
#1      Angel.mountController (package:angel_framework/src/core/server.dart:343:32)
#2      configureServer (package:project/src/routes/controller/controllers.dart:8:13)
<asynchronous suspension>
#3      Angel.configure.<anonymous closure> (package:angel_framework/src/core/server.dart:333:40)
#4      new Future.sync (dart:async/future.dart:224:31)
#5      Angel.configure (package:angel_framework/src/core/server.dart:333:19)
#6      configureServer.<anonymous closure> (package:project/src/routes/routes.dart:20:15)
<asynchronous suspension>
#7      Angel.configure.<anonymous closure> (package:angel_framework/src/core/server.dart:333:40)
#8      new Future.sync (dart:async/future.dart:224:31)
#9      Angel.configure (package:angel_framework/src/core/server.dart:333:19)
#10     createServer (package:project/app.dart:17:13)
<asynchronous suspension>
#11     HotReloader._generateServer (package:angel_hot/angel_hot.dart:133:19)
<asynchronous suspension>
#12     HotReloader.startServer (package:angel_hot/angel_hot.dart:158:21)
<asynchronous suspension>
#13     main (file:///path-to-project/bin/dev.dart:15:13)
<asynchronous suspension>
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by thosakwe** [comment]
It looks like you're trying to use controllers without reflection. In the dependency injection guide, there's mention of various ways to provide reflection to your application (most common way is `dart:mirrors`): https://docs.angel-dart.dev/v/2.x/guides/dependency-injection#enabling-dart-mirrors-or-other-reflection

Otherwise, reflection won't work. It's necessary, because otherwise you can't read annotations like `@Expose`. By default, Angel includes a `ThrowingReflector`, which will cause an exception any time you try to use reflection. If you absolutely need to avoid reflection, just use plain route groups and you'll be more than fine.

Note that if you pass a `logger` to the `Angel` constructor, it'll print a big warning if you don't pass a reflector:

```
No `reflector` was passed to the Angel constructor, so reflection will not be available.
Features like controllers, constructor dependency injection, and `ioc` require reflection,
and will not work without it.


For more, see the documentation
https://docs.angel-dart.dev/guides/dependency-injection#enabling-dart-mirrors-or-other-reflection
```

In addition, every `angel init` project contains this message in `bin/prod.dart`:

```dart
// NOTE: By default, the Runner class does not use the `MirrorsReflector`, or any
// reflector, by default.
//
// If your application is using any sort of functionality reliant on annotations or reflection,
// either include the MirrorsReflector, or use a static reflector variant.
//
// The following use cases require reflection:
// * Use of Controllers, via @Expose() or @ExposeWS()
// * Use of dependency injection into constructors, whether in controllers or plain `container.make` calls
// * Use of the `ioc` function in any route
//
// The `MirrorsReflector` from `package:angel_container/mirrors.dart` is by far the most convenient pattern,
// so use it if possible.
//
// However, the following alternatives exist:
// * Generation via `package:angel_container_generator`
// * Creating an instance of `StaticReflector`
// * Manually implementing the `Reflector` interface (cumbersome; not recommended)
//
// As of January 4th, 2018, the documentation has not yet been updated to state this,
// so in the meantime, visit the Angel chat for further questions:
//
// https://gitter.im/angel_dart/discussion
```

Let me know if this helps. But in general, don't expect Controllers to work in AOT, because they are annotation-based. Plain routes are just as good, and in fact, Controllers are just an OOP wrapper over this functionality.

**Comment by u007** [comment]
hi @thosakwe sorry im still new with dart,
do you have sample in this project that it uses the mirror reflection ?

**Comment by thosakwe** [comment]
```dart
import 'dart:async';
import 'package:angel_container/mirrors.dart';
import 'package:angel_framework/angel_framework.dart';
import 'package:angel_framework/http.dart';
import 'package:logging/logging.dart';

main() async {
  Logger.root.onRecord.listen(print);
  var app = Angel(
     logger: Logger('demo'),
     reflector: MirrorsReflector(),
  ); 
  var http = AngelHttp(app);
  await http.startServer('127.0.0.1', 3000);
  print('Listening at ${http.uri}');
}
```

**Comment by u007** [comment]
thank you, solved the mount controller

**Comment by u007** [comment]
Hi, sorry , how do i chain group with mountcontroller?
example app.group('/api/v1/'...)..mountController(...)

**Comment by u007** [comment]
really appreciate if you can give me example, right now im using this work around:
```

@Expose("/api/v1/users")
class UserController extends Controller {
...
}
```
